/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.e2e.impl.api.jooq.entity.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import org.oagi.score.e2e.impl.api.jooq.entity.tables.AsbiepSupportDoc;


/**
 * Table storing supporting documentations linked to ASBIEP records.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AsbiepSupportDocRecord extends UpdatableRecordImpl<AsbiepSupportDocRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.asbiep_support_doc.asbiep_support_doc_id</code>.
     * Primary key. Unique identifier for each supporting documentation.
     */
    public void setAsbiepSupportDocId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.asbiep_support_doc.asbiep_support_doc_id</code>.
     * Primary key. Unique identifier for each supporting documentation.
     */
    public ULong getAsbiepSupportDocId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>oagi.asbiep_support_doc.asbiep_id</code>. Foreign key.
     * References the related ASBIEP record.
     */
    public void setAsbiepId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.asbiep_support_doc.asbiep_id</code>. Foreign key.
     * References the related ASBIEP record.
     */
    public ULong getAsbiepId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>oagi.asbiep_support_doc.content</code>. The main body or
     * text content of the supporting documentation.
     */
    public void setContent(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.asbiep_support_doc.content</code>. The main body or
     * text content of the supporting documentation.
     */
    public String getContent() {
        return (String) get(2);
    }

    /**
     * Setter for <code>oagi.asbiep_support_doc.description</code>. Optional
     * description, summary, or metadata about the supporting documentation.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>oagi.asbiep_support_doc.description</code>. Optional
     * description, summary, or metadata about the supporting documentation.
     */
    public String getDescription() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AsbiepSupportDocRecord
     */
    public AsbiepSupportDocRecord() {
        super(AsbiepSupportDoc.ASBIEP_SUPPORT_DOC);
    }

    /**
     * Create a detached, initialised AsbiepSupportDocRecord
     */
    public AsbiepSupportDocRecord(ULong asbiepSupportDocId, ULong asbiepId, String content, String description) {
        super(AsbiepSupportDoc.ASBIEP_SUPPORT_DOC);

        setAsbiepSupportDocId(asbiepSupportDocId);
        setAsbiepId(asbiepId);
        setContent(content);
        setDescription(description);
        resetTouchedOnNotNull();
    }
}
