/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.e2e.impl.api.jooq.entity.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;
import org.oagi.score.e2e.impl.api.jooq.entity.Keys;
import org.oagi.score.e2e.impl.api.jooq.entity.Oagi;
import org.oagi.score.e2e.impl.api.jooq.entity.tables.Asbiep.AsbiepPath;
import org.oagi.score.e2e.impl.api.jooq.entity.tables.records.AsbiepSupportDocRecord;


/**
 * Table storing supporting documentations linked to ASBIEP records.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AsbiepSupportDoc extends TableImpl<AsbiepSupportDocRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>oagi.asbiep_support_doc</code>
     */
    public static final AsbiepSupportDoc ASBIEP_SUPPORT_DOC = new AsbiepSupportDoc();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AsbiepSupportDocRecord> getRecordType() {
        return AsbiepSupportDocRecord.class;
    }

    /**
     * The column <code>oagi.asbiep_support_doc.asbiep_support_doc_id</code>.
     * Primary key. Unique identifier for each supporting documentation.
     */
    public final TableField<AsbiepSupportDocRecord, ULong> ASBIEP_SUPPORT_DOC_ID = createField(DSL.name("asbiep_support_doc_id"), SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "Primary key. Unique identifier for each supporting documentation.");

    /**
     * The column <code>oagi.asbiep_support_doc.asbiep_id</code>. Foreign key.
     * References the related ASBIEP record.
     */
    public final TableField<AsbiepSupportDocRecord, ULong> ASBIEP_ID = createField(DSL.name("asbiep_id"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "Foreign key. References the related ASBIEP record.");

    /**
     * The column <code>oagi.asbiep_support_doc.content</code>. The main body or
     * text content of the supporting documentation.
     */
    public final TableField<AsbiepSupportDocRecord, String> CONTENT = createField(DSL.name("content"), SQLDataType.CLOB(65535).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "The main body or text content of the supporting documentation.");

    /**
     * The column <code>oagi.asbiep_support_doc.description</code>. Optional
     * description, summary, or metadata about the supporting documentation.
     */
    public final TableField<AsbiepSupportDocRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB(65535).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "Optional description, summary, or metadata about the supporting documentation.");

    private AsbiepSupportDoc(Name alias, Table<AsbiepSupportDocRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AsbiepSupportDoc(Name alias, Table<AsbiepSupportDocRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Table storing supporting documentations linked to ASBIEP records."), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>oagi.asbiep_support_doc</code> table reference
     */
    public AsbiepSupportDoc(String alias) {
        this(DSL.name(alias), ASBIEP_SUPPORT_DOC);
    }

    /**
     * Create an aliased <code>oagi.asbiep_support_doc</code> table reference
     */
    public AsbiepSupportDoc(Name alias) {
        this(alias, ASBIEP_SUPPORT_DOC);
    }

    /**
     * Create a <code>oagi.asbiep_support_doc</code> table reference
     */
    public AsbiepSupportDoc() {
        this(DSL.name("asbiep_support_doc"), null);
    }

    public <O extends Record> AsbiepSupportDoc(Table<O> path, ForeignKey<O, AsbiepSupportDocRecord> childPath, InverseForeignKey<O, AsbiepSupportDocRecord> parentPath) {
        super(path, childPath, parentPath, ASBIEP_SUPPORT_DOC);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AsbiepSupportDocPath extends AsbiepSupportDoc implements Path<AsbiepSupportDocRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AsbiepSupportDocPath(Table<O> path, ForeignKey<O, AsbiepSupportDocRecord> childPath, InverseForeignKey<O, AsbiepSupportDocRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AsbiepSupportDocPath(Name alias, Table<AsbiepSupportDocRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AsbiepSupportDocPath as(String alias) {
            return new AsbiepSupportDocPath(DSL.name(alias), this);
        }

        @Override
        public AsbiepSupportDocPath as(Name alias) {
            return new AsbiepSupportDocPath(alias, this);
        }

        @Override
        public AsbiepSupportDocPath as(Table<?> alias) {
            return new AsbiepSupportDocPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Oagi.OAGI;
    }

    @Override
    public Identity<AsbiepSupportDocRecord, ULong> getIdentity() {
        return (Identity<AsbiepSupportDocRecord, ULong>) super.getIdentity();
    }

    @Override
    public UniqueKey<AsbiepSupportDocRecord> getPrimaryKey() {
        return Keys.KEY_ASBIEP_SUPPORT_DOC_PRIMARY;
    }

    @Override
    public List<ForeignKey<AsbiepSupportDocRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ASBIEP_SUPPORT_DOC_ASBIEP_ID_FK);
    }

    private transient AsbiepPath _asbiep;

    /**
     * Get the implicit join path to the <code>oagi.asbiep</code> table.
     */
    public AsbiepPath asbiep() {
        if (_asbiep == null)
            _asbiep = new AsbiepPath(this, Keys.ASBIEP_SUPPORT_DOC_ASBIEP_ID_FK, null);

        return _asbiep;
    }

    @Override
    public AsbiepSupportDoc as(String alias) {
        return new AsbiepSupportDoc(DSL.name(alias), this);
    }

    @Override
    public AsbiepSupportDoc as(Name alias) {
        return new AsbiepSupportDoc(alias, this);
    }

    @Override
    public AsbiepSupportDoc as(Table<?> alias) {
        return new AsbiepSupportDoc(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AsbiepSupportDoc rename(String name) {
        return new AsbiepSupportDoc(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AsbiepSupportDoc rename(Name name) {
        return new AsbiepSupportDoc(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AsbiepSupportDoc rename(Table<?> name) {
        return new AsbiepSupportDoc(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AsbiepSupportDoc where(Condition condition) {
        return new AsbiepSupportDoc(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AsbiepSupportDoc where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AsbiepSupportDoc where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AsbiepSupportDoc where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AsbiepSupportDoc where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AsbiepSupportDoc where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AsbiepSupportDoc where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AsbiepSupportDoc where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AsbiepSupportDoc whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AsbiepSupportDoc whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
